# This is a basic workflow to help you get started with Actions

name: 01-building-blocks

on: 
 push:
 workflow_dispatch:


jobs: 
   myfirstjob:
       runs-on: ubuntu-latest
       steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Printing folders
          - run: ls
          
   secoundjob:
         runs-on: ubuntu-latest
         steps:
           - name : Multi-line bash
             run: |
                  echo "I am"
                  echo "a multi-line"
                  echo "script."
            
         
        
       
              





