# This is a basic workflow to help you get started with Actions

name: 01-building-blocks

on: push



jobs: 
   myfirstjob:
       runs-on: ubuntu-latest
       steps: 
          - run: echo "Hello World"
        
       
              





